services:
  mysql:
    image: mysql:9.5
    container_name: mysql-goat-tutorats
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: Base_GoatTutorats
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

volumes:
  mysql-data:
