name: Docker Build and Push

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: github-runner-scale-set-goat-tutorats

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Buildx builder pointing to remote BuildKit
              run: |
                  export BUILDKIT_HOST="tcp://buildkit.techops.tf:31234"
                  docker buildx create --name remote-buildkit --driver remote || true
                  docker buildx use remote-buildkit
                  docker buildx inspect --bootstrap
            - name: Login to Harbor
              uses: docker/login-action@v2
              with:
                  registry: harbor.techops.tf
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}

            - name: Build and push Docker image to Harbor
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                  builder: remote-buildkit
                  context: ./goatTutorats
                  file: ./goatTutorats/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: |
                      harbor.techops.tf/techops/goat-tutorats:latest
                      harbor.techops.tf/techops/goat-tutorats:${{ github.sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  provenance: false

            - name: Get image digest
              run: echo "IMAGE_DIGEST=${{ steps.build-and-push.outputs.digest }}" >> $GITHUB_ENV

            - name: Install Cosign
              uses: sigstore/cosign-installer@main

            - name: Check Cosign version
              run: cosign version

            - name: Sign Docker image with Cosign
              env:
                  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
                  COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                  IMAGE_DIGEST: ${{ steps.build-and-push.outputs.digest }}
              run: |
                  echo "$COSIGN_PRIVATE_KEY" > cosign.key
                  chmod 600 cosign.key
                  IMAGE_REF="harbor.techops.tf/techops/goat-tutorats@${IMAGE_DIGEST}"
                  cosign sign --key cosign.key $IMAGE_REF
                  cosign sign --key cosign.key harbor.techops.tf/techops/goat-tutorats:${{ github.sha }}
                  cosign sign --key cosign.key harbor.techops.tf/techops/goat-tutorats:latest
                  cosign verify --key cosign.key harbor.techops.tf/techops/goat-tutorats@${IMAGE_DIGEST}
                  rm -f cosign.key